### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by Hayden2147483647** [igentuman/multi-builder-tool#1]
Running environment:
Minecraft 1.12.2
Minecraft Forge 14.23.5.2855
Description:

Crashed when mouse hover over on JEI to look up recipe

[crash-2023-02-17_16.24.46-client.txt](https://github.com/igentuman/multi-builder-tool/files/10762985/crash-2023-02-17_16.24.46-client.txt)

**Comment by igentuman** [comment]
Recipe for MBTool?

**Comment by igentuman** [comment]
In a stack trace i see nothing pointing into my mod. I need more details.

**Comment by Hayden2147483647** [comment]
My apologies. I realize I had a mod installed that broke the game when I downloaded your mod at the same time.
Keep up with the amazing work, once again sorry for creating an issue for this
